Bugfix - Ignore workspace dependencies
JonShort/npm-bumpall pull request #16
Opened 2022-12-23 16:25 UTC by JonShort

This is the first step for #15, where we ignore workspace dependencies.

Eventually we can build in a "workspace mode" or similar which will update workspace dependencies.

2022-12-30 16:28 UTC, JonShort commented on src/package.rs
> +        let _location = if src.len() > 4 && &src[1..3] == ":\\" {
Just wanted to make this check a little more specific to try and avoid any edge-cases around `:\\` appearing elsewhere in the string

2022-12-30 16:28 UTC, JonShort commented on src/package.rs
> +        let install_dir_name: String = segments.collect::<Vec<&str>>().join(":");
👉  Since this is the last item in the parseable string, we can avoid any potential edge-cases around directories with `:` in by collecting into a string

It's extremely unlikely, but not much extra effort

2023-01-03 20:41 UTC, JonShort commented
@jaysc - Thoughts on this? I'll try it on a _workspace heavy repo_ tomorrow and see how it does 🧑‍🚀

2023-01-04 20:02 UTC, jaysc requested changes
Seems to be a bug on windows where it's preserving the return character for `install_dir_name`.
On windows, it produces `"npm_dir\r"`

You should trim the line like:
```rust
let install_dir_name: String = segments.collect::<Vec<&str>>().join(":").trim().to_string();
```

I think everything else looks fine.

2023-01-28 17:19 UTC, jaysc approved these changes

2023-02-11 15:00 UTC, merged